config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'

  namespace :public do
    resources :users, only:[:index,:show,:edit,:update,:destroy] do
      member do
        get :user_columns
        get :user_clubs
        get :favorites
        patch :release
        patch :nonrelease
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :clubs, only:[:index,:new,:create,:show,:edit,:update,:destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only:[:index,:show,:edit,:update,:destroy]
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
  
end

app/models/club.rb
class Club < ApplicationRecord
  
  belongs_to :user, optional: true
  
  validates :club_type, presence: true
  validates :club_name, presence: true
  
end

app/models/column.rb
class Column < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @column = Column.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @column = Column.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @column = Column.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @column = Column.where("title LIKE?","%#{word}%")
    else
      @column = Column.all
    end
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :column
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :column
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :columns, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :clubs, dependent: :destroy
         
         # フォローをした、されたの関係
         has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         # 一覧画面で使う
         has_many :followings, through: :relationships, source: :followed
         has_many :followers, through: :reverse_of_relationships, source: :follower
         
         enum status:{nonreleased: 0, released: 1}
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < ApplicationController
end

app/controllers/admin/columns_controller.rb
class Admin::ColumnsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @columns = Column.all.page(params[:page]).per(10)
  end

  def new
    @column = Column.new
  end

  def create
    @column = Column.new(column_params)
    if @column.save
      redirect_to admin_column_path(@column)
      flash[:notice] = '新しいコラムを登録しました。'
    else
    render "new"
    end
  end

  def show
    @column = Column.find(params[:id])
  end

  def edit
    @column = Column.find(params[:id])
  end

  def update
    @column = Column.find(params[:id])
    if @column.update(column_params)
      redirect_to admin_column_path(@column.id)
      flash[:notice] = 'コラムを編集しました'
    else
      render :"show"
    end
  end
  
  def destroy
    @column = Column.find(params[:id])
    @column.destroy
    redirect_to admin_columns_path
  end

  private
  
  def column_params
  	params.require(:column).permit(:title,:body,:is_active,:image)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
  end

  def about
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      flash[:notice] = '会員情報が更新されました。'
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,])
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @columns = Column.looks(params[:search], params[:word])
    end
  end
  
end

app/helpers/admin/clubs_helper.rb
module Admin::ClubsHelper
end

app/helpers/admin/columns_helper.rb
module Admin::ColumnsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/homes/top.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2"style="margin-top: 100px;">
    <div class="text-center">
      <h2 class=my-5><i class="fas fa-golf-ball"></i> Golfi</h2>

      <h6 class=my-5>
        管理者様</br>
        ユーザやコラムを編集したり</br>
        削除したりすることができます。</br>
        </br>
      </h6>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="col-md-8 offset-md-2"> 
    <div class="shadow p-3 mb-5 bg-white rounded">

    <h2 class="p-3 mb-2 bg-dark text-white">検索結果</h2>
    <p id="notice"></p>
    <table class="table table-hover">
      
    <!--検索対象モデルがUserの時 -->
    <% if @range == "User" %>
      <thead>
        <tr class="table-secondary">
          <th>氏名</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tr class="table-borderless">
          <% if user_signed_in? %>
            <td><%= link_to user.name, public_user_path(user.id) %></td>
            <td>follows <u><%= link_to user.followings.count, public_user_followings_path(user_id: user.id) %></u></td>
            <td>followers <u><%= link_to user.followers.count, public_user_followers_path(user_id: user.id) %></u></td>
          <% elsif admin_signed_in? %>
            <td><%= link_to user.name, admin_user_path(user.id) %></td>
            <td>follows <%= user.followings.count %></td>
            <td>followers <%= user.followers.count %></td>
            
          <% end %>
        </tr>
      <% end %>
     
      
    <!--検索対象モデルがUserではない時(= 検索対象モデルがColumnの時) -->  
    <% else %>
      <thead>
        <tr class="table-secondary">
          <th class="col-md-6">Title</th>
          <th class="col-md-1"></th>
          <th class="col-md-1"></th>
        </tr>
      </thead>
      <% @columns.each do |column| %>
      <tr class="table-borderless">
        <td>
          <% if user_signed_in? %>
            <%= link_to column.title, public_column_path(column) %>
          <% elsif admin_signed_in? %>
          　<%= link_to column.title, admin_column_path(column) %>
          <% end %>
        </td>
        <td>
          <% if user_signed_in? %>
            <% if column.favorited_by?(current_user) %>
              <p>
                <%= link_to public_column_favorites_path(column), class: "btn btn-danger", method: :delete, remote: true do %>
                  <i class="fa fa-heart"></i><%= column.favorites.count %>
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to public_column_favorites_path(column), class: "btn btn-outline-secondary", method: :post, remote: true do %>
                  <i class="far fa-heart"></i><%= column.favorites.count %>
                <% end %>
              </p>
            <% end %>
          <% else %>
            ♡<%= column.favorites.count %>
          <% end %>
        </td>
        <td><i class="far fa-comment"></i><%= link_to "#{column.post_comments.count}", public_column_path(column.id) %></td>
      </tr>
      <% end %>
    <% end %>
    </table>
    </div>
  </div>
</div>