config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'

  namespace :public do
    resources :users, only:[:index,:show,:edit,:update,:destroy] do
      member do
        get :user_columns
        get :user_clubs
        get :favorites
        patch :release
        patch :nonrelease
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :clubs, only:[:index,:new,:create,:show,:edit,:update,:destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only:[:index,:show,:edit,:update,:destroy]
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/column.rb
class Column < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @column = Column.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @column = Column.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @column = Column.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @column = Column.where("title LIKE?","%#{word}%")
    else
      @column = Column.all
    end
  end
  
end

app/controllers/admin/columns_controller.rb
class Admin::ColumnsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @columns = Column.all.page(params[:page]).per(10)
  end

  def new
    @column = Column.new
  end

  def create
    @column = Column.new(column_params)
    if @column.save
      redirect_to admin_column_path(@column)
      flash[:notice] = '新しいコラムを登録しました。'
    else
    render "new"
    end
  end

  def show
    @column = Column.find(params[:id])
  end

  def edit
    @column = Column.find(params[:id])
  end

  def update
    @column = Column.find(params[:id])
    if @column.update(column_params)
      redirect_to admin_column_path(@column.id)
      flash[:notice] = 'コラムを編集しました'
    else
      render :"show"
    end
  end
  
  def destroy
    @column = Column.find(params[:id])
    @column.destroy
    redirect_to admin_columns_path
  end

  private
  
  def column_params
  	params.require(:column).permit(:title,:body,:is_active,:image)
  end

end

app/helpers/admin/columns_helper.rb
module Admin::ColumnsHelper
end

app/views/admin/columns/create.html.erb
<h1>Admin::Columns#create</h1>
<p>Find me in app/views/admin/columns/create.html.erb</p>

app/views/admin/columns/edit.html.erb
<div class="container">
  <div class="col-md-8 offset-md-2"> 
    <div class="shadow p-3 mb-5 bg-white rounded">
      
      <h2 class="p-3 mb-2 bg-dark text-white">コラム編集</h2>
      <p id="notice"></p>
       
      <%= form_with model:@column, url: admin_column_path, method: :patch do |f| %>
        <div class="form-group", style="text-align: center;",>
          <p id="notice"></p>
            <<%= f.label :Image %>>
            <br><%= f.file_field :image, accept: "image/*" %>
        </div>  
        <div class="form-group", style="text-align: center;">
          <div class="col-sm-12">
          <p id="notice"></p>
            <<%= f.label :Title %>>
            <br><%= f.text_field :title, :size=>"50" %>
          </div>
          <div class="form-group", style="text-align: center;">
            <p id="notice"></p>
            <<%= f.label :Column %>>
            <br><%= f.text_area :body, rows: '10', cols: '50' %></td>
          </div>
          <div class="form-group" style="text-align: center;">
            <p id="notice"></p>
            <%= f.submit ' 変更を保存 ' , class: "btn btn-outline-success" %>
          </div>
        </div>
      <% end %>
        
    </div>
  </div>
</div>

app/views/admin/columns/index.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="col-md-8 offset-md-2"> <%#.offset-md-1 は .col-md-9 を 1 カラムぶん右に移動%>
    <div class="shadow p-3 mb-5 bg-white rounded">

 
  <h2 class="p-3 mb-2 bg-dark text-white">コラム一覧</h2>
  
      <p id="notice"></p>
      <table class="table table-hover">
        <tr class="table-secondary">
          <th class="col-md-2">Name</th>
          <th class="col-md-6">Title</th>
          <th class="col-md-1"></th>
          <th class="col-md-1"></th>
        </tr>
          <% @columns.each do |column| %>
            <tr class="table-borderless">
              <td><%= link_to column.user.name, admin_user_path(column.user.id) %></td>
              <td><%= link_to column.title, admin_column_path(column) %></td>
              <td>
                <i class="far fa-heart"></i><%= column.favorites.count %>
              </td>
              <td><i class="far fa-comment"></i><%= link_to "#{column.post_comments.count}", admin_column_path(column.id) %></td>
            </tr>
            <% end %>
      </table>
    </div>
    
<ul class="pagination justify-content-center">
<%= paginate @columns %>
</ul>

  </div>
</div>

app/views/admin/columns/new.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="col-md-8 offset-md-2"> 
    <div class="shadow p-3 mb-5 bg-white rounded">
      <div class="row">
        <div class="col-md-8 offset-1"style="margin-top: 30px;">
        <h2 class="p-3 mb-2 bg-dark text-white">コラム新規登録</h2>
        <p id="notice"></p>
        <%= form_with model:@column, url: admin_columns_path, method: :post do |f| %>
          <form>
            <div class="form-group", style="text-align: left;",>
              <p id="notice"></p>
               <%= f.label :コラム画像 %>
                <%= f.file_field :image, placeholder: "選択されていません", accept: "image/*" %>
            </div>
            <div class="form-group">
              <div class="col-sm-10">
              <p id="notice"></p>
               <%= f.label :コラム名 %>
                <%= f.text_field :title, placeholder: "コラム名" %>
              </div>
            </div>
            <div class="form-group">
              <p id="notice"></p>
               <%= f.label :コラム %>
                <%= f.text_area :body, placeholder: "ここにコラムを記述します" %>
            </div>
            <div class="form-group" style="text-align: center;">
                <p id="notice"></p>
                <%= f.submit "新規登録", class: "btn btn-outline-success"  %>
            </div>
          </form>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/columns/show.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="shadow p-3 mb-5 bg-white rounded">

    <h2 class="p-3 mb-2 bg-dark text-white">コラム詳細</h2>

    <div class="row">

      <div class="col-md-3" style="text-align: left;">
　　　  <table class="table">
      </div>

      <div class="col-md-8", style="margin-top: 25px;">
        <tr>
          <% if @column.image.attached? %>
            <%= image_tag @column.image, size: "325x325" %>
          <% else %>
            <%= image_tag asset_path("no_image.jpg"), size: "325x325" %>
          <% end %>
        </tr>
         </table>
      </div>
    <div class="col-md-8 offset-1"style="margin-top: 50px;">
    <table class="table">
      <tbody>
        <tr><td>Name</td><td><%= link_to @column.user.name, admin_user_path(@column.user.id) %></td></tr>
        <tr><td>Title</td><td><%= @column.title %></td></tr>
        <tr><td>Column</td><td><%= @column.body %></td></tr>
        <tr>
          <td>
            <p><i class="far fa-heart"></i> <%= @column.favorites.count %></p>
          <td>
        </tr>
      　<tr>
        　<td class="col-md-1"><%= link_to "一覧に戻る", admin_columns_path, class: "btn btn-outline-success" %></td>
          <td class="col-md-3">
            <%= link_to '編集する', edit_admin_column_path(@column.id), class: "btn btn-outline-success w-75" %>
            <%= link_to "削除", admin_column_path(@column), class: "btn btn-outline-danger", method: :delete %>
          </td>
        </tr>
      </tbody>
    </table>
    </div>

    <div style="text-align: left;margin-left:40px;margin-top:40px;left;margin-right:400px;margin-bottom:20px;">
      <p>Comment：<i class="far fa-comment"></i> <%= @column.post_comments.count %></p>
      <% @column.post_comments.each do |post_comment| %>
        <br><%= link_to post_comment.user.name, admin_user_path(post_comment.user.id) %>
        <%= post_comment.created_at.strftime('%Y/%m/%d(%a) %X') %>
        <br><%= post_comment.comment %>
          <%= link_to "削除", admin_column_post_comment_path(post_comment.column, post_comment), class: "btn btn-outline-danger", method: :delete %>
        <br>----------------------------------------------------------------------------------
      <% end %>
    </div>

    </div>
  </div>
</div>