config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'

  namespace :public do
    resources :users, only:[:index,:show,:edit,:update,:destroy] do
      member do
        get :user_columns
        get :user_clubs
        get :favorites
        patch :release
        patch :nonrelease
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :clubs, only:[:index,:new,:create,:show,:edit,:update,:destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only:[:index,:show,:edit,:update,:destroy]
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :columns, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :clubs, dependent: :destroy
         
         # フォローをした、されたの関係
         has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         # 一覧画面で使う
         has_many :followings, through: :relationships, source: :followed
         has_many :followers, through: :reverse_of_relationships, source: :follower
         
         enum status:{nonreleased: 0, released: 1}
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      flash[:notice] = '会員情報が更新されました。'
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="col-md-8 offset-md-2"> <%#.offset-md-1 は .col-md-9 を 1 カラムぶん右に移動%>
    <div class="shadow p-3 mb-5 bg-white rounded">

<%# form_withを使い、情報を取得するモデル、rails routesで調べたURL、メソッドを指定して、'f.text_field'でデータを引っ張ってきてください。%>
<%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
<table class="table table-hover">

      <h2 class="p-3 mb-2 bg-dark text-white">会員情報編集 </h2>
      

      <tbody>
      <tr><td>ID</td><td><%= @user.id %></td></tr>
      <tr><td>Name</td><td><%= f.text_field :name %></td></tr>
      <tr><td>e-mail</td><td><%= f.text_field :email %></td></tr>
    </tbody>
  </table>
  
  <div class="text-center">
   <%= f.submit '変更を保存', class: "btn btn-outline-success w-50" %>
  </div>
  
<% end %>

    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="col-md-8 offset-md-2"> 
    <div class="shadow p-3 mb-5 bg-white rounded">

  <h2 class="p-3 mb-2 bg-dark text-white">ユーザ一覧</h2>
  <p id="notice"></p>
  <table class="table table-hover">
    <thead>
      <tr class="table-secondary">
        <th>ID</th>
        <th>Name</th>
        <th>e-mail</th>
      </tr>
    </thead>
      <% @users.each do |user| %><%# @publics = Public.allですべてのPublicユーザーの情報を取得して、順番に並べて表示 %>
    <tbody>
      <tr>
        <td class="col-md-1"><%= user.id %></td>
        <td class="col-md-2"><%= link_to user.name, admin_user_path(user.id) %></td>
        <td class="col-md-3"><%= user.email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>
</div>

app/views/admin/users/show.html.erb
<div class="container" style="margin-top: 50px;">
  <div class="row">
    <div class="col-md-8 offset-md-2"> <%#.offset-md-1 は .col-md-9 を 1 カラムぶん右に移動%>
      <div class="shadow p-3 mb-5 bg-white rounded">



  <table class="table">
    <thead>
      <h2 class="p-3 mb-2 bg-dark text-white">会員詳細</h2>
    </thead>

    <tbody>
      <tr><td>ID</td><td><%= @user.id %></td></tr>
      <tr><td>Name</td><td><%= @user.name %></td></tr>
      <tr><td>e-mail</td><td><%= @user.email %></td></tr>
    </tbody>
  </table>

  <div class="text-center">
   <%= link_to '編集する', edit_admin_user_path(@user.id), class: "btn btn-outline-success w-25" %>
   <%= link_to "削除", admin_user_path(@user), class: "btn btn-outline-danger", method: :delete %>
  </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/users/update.html.erb
<h1>Admins::Users#update</h1>
<p>Find me in app/views/admins/ers/update.html.erb</p>