config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'

  namespace :public do
    resources :users, only:[:index,:show,:edit,:update,:destroy] do
      member do
        get :user_columns
        get :user_clubs
        get :favorites
        patch :release
        patch :nonrelease
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :clubs, only:[:index,:new,:create,:show,:edit,:update,:destroy]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :users, only:[:index,:show,:edit,:update,:destroy]
    resources :columns, only:[:index,:new,:create,:show,:edit,:update,:destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
  
end

app/models/club.rb
class Club < ApplicationRecord
  
  belongs_to :user, optional: true
  
  validates :club_type, presence: true
  validates :club_name, presence: true
  
end

app/models/column.rb
class Column < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @column = Column.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @column = Column.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @column = Column.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @column = Column.where("title LIKE?","%#{word}%")
    else
      @column = Column.all
    end
  end
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :column
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :column
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :columns, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :clubs, dependent: :destroy
         
         # フォローをした、されたの関係
         has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         # 一覧画面で使う
         has_many :followings, through: :relationships, source: :followed
         has_many :followers, through: :reverse_of_relationships, source: :follower
         
         enum status:{nonreleased: 0, released: 1}
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/admin/clubs_controller.rb
class Admin::ClubsController < ApplicationController
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
  end

  def about
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      flash[:notice] = '会員情報が更新されました。'
    else
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,])
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @columns = Column.looks(params[:search], params[:word])
    end
  end
  
end

app/helpers/admin/clubs_helper.rb
module Admin::ClubsHelper
end

app/helpers/admin/columns_helper.rb
module Admin::ColumnsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-md-12" style="text-align: center; line-height: 100px;">
        <p>CopyRight Golfi.inc</p>
      </div>
    </div>
  </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

<nav class="navbar navbar-expand-lg bg-white">
<div class="container">

<% if user_signed_in? %> <%# ここから次のelsifの列にいくまでがpublic_userのヘッダー%>

  <h2 class="nav-link text-left">
    <%= link_to root_path, class: "nav-link text-dark" do %>
      <i class="fas fa-golf-ball"></i>Golfi
    <% end %>
  </h2>

  <li class="nav-link text-dark"><%= link_to "My page", public_user_path(current_user), class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "Column", public_columns_path, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= render "layouts/search" %></li>

<% elsif admin_signed_in? %>

  <h2 class="nav-link text-left">
    <%= link_to admin_root_path, class: "nav-link text-dark" do %>
      <i class="fas fa-golf-ball"></i> Golfi
    <% end %>
  </h2>

  <li class="nav-link text-dark"><%= link_to "Column", admin_columns_path, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "User", admin_users_path, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "Log out", destroy_admin_session_path, method: :delete, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= render "layouts/search" %></li>

<% else %>

  <h2 class="nav-link text-left">
    <%= link_to root_path, class: "nav-link text-dark" do %>
      <i class="fas fa-golf-ball"></i> Golfi
    <% end %>
  </h2>

  <li class="nav-link text-dark"><%= link_to "About", about_path, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "Column", public_columns_path, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "Sign up" ,new_user_registration_path, class: "nav-link text-dark" %></li>

  <li class="nav-link text-dark"><%= link_to "Log in" ,new_user_session_path, class: "nav-link text-dark" %></li>

<% end %>

</div>
</nav>

</header>

app/views/layouts/_search.html.erb
<div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Column']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"], ["前方一致","forward_match"], ["後方一致","backward_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Golfi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('golf-player.ico') %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render "layouts/header" %>
    <%= yield %>
    
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    
  </body>
</html>